### PR TITLE
Setup Docker and pipenv

### PR DESCRIPTION
**Pull request by DesignrKnight**
- Docker runs at port 5000. It is mapped to port 8000 within the container where the server runs
- Present Docker container setup is made to use SQLite as db

### CODE REVIEW

**Comment by DesignrKnight** [comment]
To use pipenv
- pipenv shell
- pipenv install

Then proceed as usual. pipenv handles the creation of environemnt

**Comment by DesignrKnight** [comment]
Linked Issues
- #2 
- #3 

@kautukkundan , kindly review

**Comment by DesignrKnight** [comment]
Hey, any updates?

**Comment by kautukkundan** [comment]
sorry for the late response, had been stuck with something else

I feel we can have an option of choosing which db to use instead of an opinionated approach. As for now I have marked the PR as hacktoberfest-accepted so that it counts to your progress. I will take a look at it once again in some time. 
please let me know your thoughts

**Pull request merged**
